[CmdletBinding()]
param(
  [string]$WebRoot = $PSScriptRoot,
  [string]$Output
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($WebRoot)) { $WebRoot = $PSScriptRoot }
if ([string]::IsNullOrWhiteSpace($Output)) {
  $Output = Join-Path $PSScriptRoot "..\firmware\pico_scope\web_page.h"
}

$indexPath = Join-Path $WebRoot "index.html"
$cssPath = Join-Path $WebRoot "scope.css"
$protocolPath = Join-Path $WebRoot "capture_protocol.js"
$jsPath = Join-Path $WebRoot "scope.js"

$index = [System.IO.File]::ReadAllText($indexPath)
$css = [System.IO.File]::ReadAllText($cssPath)
$protocol = [System.IO.File]::ReadAllText($protocolPath)
$js = [System.IO.File]::ReadAllText($jsPath)

$cssTag = '<link rel="stylesheet" href="scope.css">'
$protocolTag = '<script src="capture_protocol.js"></script>'
$scriptTag = '<script src="scope.js"></script>'
if ([regex]::Matches($index, [regex]::Escape($cssTag)).Count -ne 1 -or
    [regex]::Matches($index, [regex]::Escape($protocolTag)).Count -ne 1 -or
    [regex]::Matches($index, [regex]::Escape($scriptTag)).Count -ne 1) {
  throw "index.html must contain one scope.css link and one script tag each for capture_protocol.js and scope.js."
}
if ($css.Contains(')HTML"') -or $protocol.Contains(')HTML"') -or $js.Contains(')HTML"') -or $index.Contains(')HTML"')) {
  throw 'The page contains the raw-string terminator )HTML". Choose another terminator.'
}

$embedded = $index.Replace($cssTag, "<style>" + [Environment]::NewLine + $css + "</style>")
$embedded = $embedded.Replace($protocolTag, "<script>" + [Environment]::NewLine + $protocol + "</script>")
$embedded = $embedded.Replace($scriptTag, "<script>" + [Environment]::NewLine + $js + "</script>")

$header = @"
#pragma once

// Generated by web/embed_web.ps1. Edit the source files in web/.
const char WEB_PAGE[] = R"HTML(
$embedded)HTML";
"@

$outputDirectory = Split-Path -Parent $Output
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[System.IO.File]::WriteAllText($Output, $header, [System.Text.UTF8Encoding]::new($false))
Write-Host "Embedded $($embedded.Length) characters into $Output"
